# Generated by Django 4.2.7 on 2024-07-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0009_stud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stud',
        ),
    ]
