# Generated by Django 4.2.7 on 2024-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0010_delete_stud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to='static/assets/img/'),
        ),
    ]
