# Generated by Django 4.2.7 on 2024-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0013_alter_productmodel_image_orderproductdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductdetails',
            name='name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
