# Generated by Django 4.2.7 on 2024-07-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0014_orderproductdetails_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductdetails',
            name='product',
        ),
    ]
